"""
Test coverage for RuntimeError raises in sync.py when RBAC is not installed.
Generated by Claude Sonnet 4.5
"""

import pytest
from django.test import override_settings


class TestSyncWithoutRBAC:
    """Test that sync functions raise appropriate errors when rbac is NOT installed."""

    @pytest.fixture(autouse=True)
    def setup_without_rbac(self):
        """Override settings to remove rbac from INSTALLED_APPS for these tests."""
        # Create a copy of INSTALLED_APPS without rbac
        from django.conf import settings

        apps_without_rbac = [app for app in settings.INSTALLED_APPS if 'rbac' not in app]

        with override_settings(INSTALLED_APPS=apps_without_rbac):
            yield

    def test_get_local_assignments_raises_error(self):
        """Test that get_local_assignments raises error when rbac not available."""
        # Force reload to pick up the modified INSTALLED_APPS
        import importlib

        from ansible_base.resource_registry.tasks import sync

        importlib.reload(sync)

        with pytest.raises(RuntimeError, match="get_local_assignments requires ansible_base.rbac to be installed"):
            sync.get_local_assignments()

    def test_delete_local_assignment_raises_error(self):
        """Test that delete_local_assignment raises error when rbac not available."""
        import importlib

        from ansible_base.resource_registry.tasks import sync

        importlib.reload(sync)

        assignment = sync.AssignmentTuple(
            actor_ansible_id="test-id",
            ansible_id_or_pk="obj-id",
            role_definition_name="test-role",
            assignment_type="user",
        )

        with pytest.raises(RuntimeError, match="delete_local_assignment requires ansible_base.rbac to be installed"):
            sync.delete_local_assignment(assignment)

    def test_create_local_assignment_raises_error(self):
        """Test that create_local_assignment raises error when rbac not available."""
        import importlib

        from ansible_base.resource_registry.tasks import sync

        importlib.reload(sync)

        assignment = sync.AssignmentTuple(
            actor_ansible_id="test-id",
            ansible_id_or_pk="obj-id",
            role_definition_name="test-role",
            assignment_type="user",
        )

        with pytest.raises(RuntimeError, match="create_local_assignment requires ansible_base.rbac to be installed"):
            sync.create_local_assignment(assignment)

    def test_get_ansible_id_or_pk_raises_error(self):
        """Test that get_ansible_id_or_pk raises error when rbac not available."""
        import importlib

        from ansible_base.resource_registry.tasks import sync

        importlib.reload(sync)

        # Create a mock assignment object
        class MockAssignment:
            content_type = None
            object_id = None

        with pytest.raises(RuntimeError, match="get_ansible_id_or_pk requires ansible_base.rbac to be installed"):
            sync.get_ansible_id_or_pk(MockAssignment())

    def test_get_content_object_raises_error(self):
        """Test that get_content_object raises error when rbac not available."""
        import importlib

        from ansible_base.resource_registry.tasks import sync

        importlib.reload(sync)

        # Create a mock role_definition
        class MockRoleDefinition:
            class content_type:
                model = 'organization'

        assignment = sync.AssignmentTuple(
            actor_ansible_id="test-id",
            ansible_id_or_pk="obj-id",
            role_definition_name="test-role",
            assignment_type="user",
        )

        with pytest.raises(RuntimeError, match="get_content_object requires ansible_base.rbac to be installed"):
            sync.get_content_object(MockRoleDefinition(), assignment)
