# Generated by Django 4.2.8 on 2024-03-18 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_city'),
    ]

    operations = [
        # Removed team admins and user relationships
    ]
